feature:
  test_size: 20
  shuffle: True

model_parameter:
  n_estimators: 330
  max_depth: 33
  learning_rate: 0.1
  subsample: 0.63
  colsample_bytree: 0.5
  gamma: 0
  min_child_weight: 1
  reg_alpha: 0
  reg_lambda: 1
  objective: 'reg:squarederror'
  random_state: 42

